_core:
  default_config_hash: nrEzeou9YzSAPCAxvoNWWhySV_5j-IEm-3hEYjiIqBY
allowed_tags:
  - div
  - span
  - h2
  - h3
  - h4
  - h5
  - h6
class_list: ''
label_tag_enabled: 1
label_class_enabled: 1
label_class_select_enabled: 0
label_value_enabled: 1
langcode: es
